"""
Aggregate imports for schemas to allow easy access like from app.schemas import SomeSchema
"""

from .base import (
    UserRole,
    PlatformUserRole,
    OrganizationStatus,
    PlanType,
    OrganizationBase,
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationInDB,
    OrganizationLicenseCreate,
    OrganizationLicenseResponse,
    PasswordChangeRequest,
    ForgotPasswordRequest,
    PasswordResetRequest,
    PasswordChangeResponse,
    UserBase,
    UserCreate,
    UserUpdate,
    UserInDB,
    UserLogin,
    Token,
    TokenData,
    PlatformUserBase,
    PlatformUserCreate,
    PlatformUserUpdate,
    PlatformUserInDB,
    PlatformUserLogin,
    PlatformToken,
    OTPRequest,
    OTPVerifyRequest,
    OTPResponse,
    VendorBase,
    VendorCreate,
    VendorUpdate,
    VendorInDB,
    CustomerBase,
    CustomerCreate,
    CustomerUpdate,
    CustomerInDB,
    ProductBase,
    ProductCreate,
    ProductUpdate,
    ProductInDB,
    StockBase,
    StockCreate,
    StockUpdate,
    StockInDB,
    BulkStockRequest,
    EmailNotificationBase,
    EmailNotificationCreate,
    EmailNotificationInDB,
    PaymentTermBase,
    PaymentTermCreate,
    PaymentTermUpdate,
    PaymentTermInDB,
    BulkImportResponse,
    BulkImportError,
    DetailedBulkImportResponse
)

from .company import (
    CompanyBase,
    CompanyCreate,
    CompanyUpdate,
    CompanyInDB,
    CompanyResponse,
    CompanyListResponse,
    CompanyValidationError,
    CompanyErrorResponse,
    CompanyBulkImportResponse
)

from .vouchers import (
    VoucherItemBase, VoucherItemWithTax, VoucherBase,
    PurchaseVoucherItemCreate, PurchaseVoucherItemInDB,
    PurchaseVoucherCreate, PurchaseVoucherUpdate, PurchaseVoucherInDB,
    SalesVoucherItemCreate, SalesVoucherItemInDB,
    SalesVoucherCreate, SalesVoucherUpdate, SalesVoucherInDB,
    PurchaseOrderItemCreate, PurchaseOrderItemInDB,
    PurchaseOrderCreate, PurchaseOrderUpdate, PurchaseOrderInDB,
    SalesOrderItemCreate, SalesOrderItemInDB,
    SalesOrderCreate, SalesOrderUpdate, SalesOrderInDB,
    GRNItemCreate, GRNItemInDB, GRNCreate, GRNUpdate, GRNInDB,
    DeliveryChallanItemCreate, DeliveryChallanItemInDB,
    DeliveryChallanCreate, DeliveryChallanUpdate, DeliveryChallanInDB,
    ProformaInvoiceItemCreate, ProformaInvoiceItemInDB,
    ProformaInvoiceCreate, ProformaInvoiceUpdate, ProformaInvoiceInDB,
    QuotationItemCreate, QuotationItemInDB,
    QuotationCreate, QuotationUpdate, QuotationInDB
)

__all__ = [
    # Base schemas
    "UserRole",
    "PlatformUserRole",
    "OrganizationStatus",
    "PlanType",
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationInDB",
    "OrganizationLicenseCreate",
    "OrganizationLicenseResponse",
    "PasswordChangeRequest",
    "ForgotPasswordRequest",
    "PasswordResetRequest",
    "PasswordChangeResponse",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    "UserLogin",
    "Token",
    "TokenData",
    "PlatformUserBase",
    "PlatformUserCreate",
    "PlatformUserUpdate",
    "PlatformUserInDB",
    "PlatformUserLogin",
    "PlatformToken",
    "OTPRequest",
    "OTPVerifyRequest",
    "OTPResponse",
    "VendorBase",
    "VendorCreate",
    "VendorUpdate",
    "VendorInDB",
    "CustomerBase",
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerInDB",
    "ProductBase",
    "ProductCreate",
    "ProductUpdate",
    "ProductInDB",
    "StockBase",
    "StockCreate",
    "StockUpdate",
    "StockInDB",
    "BulkStockRequest",
    "EmailNotificationBase",
    "EmailNotificationCreate",
    "EmailNotificationInDB",
    "PaymentTermBase",
    "PaymentTermCreate",
    "PaymentTermUpdate",
    "PaymentTermInDB",
    "BulkImportResponse",
    "BulkImportError",
    "DetailedBulkImportResponse",
    
    # Company schemas
    "CompanyBase",
    "CompanyCreate",
    "CompanyUpdate",
    "CompanyInDB",
    "CompanyResponse",
    "CompanyListResponse",
    "CompanyValidationError",
    "CompanyErrorResponse",
    "CompanyBulkImportResponse",
    
    # Voucher schemas
    "VoucherItemBase", "VoucherItemWithTax", "VoucherBase",
    "PurchaseVoucherItemCreate", "PurchaseVoucherItemInDB",
    "PurchaseVoucherCreate", "PurchaseVoucherUpdate", "PurchaseVoucherInDB",
    "SalesVoucherItemCreate", "SalesVoucherItemInDB",
    "SalesVoucherCreate", "SalesVoucherUpdate", "SalesVoucherInDB",
    "PurchaseOrderItemCreate", "PurchaseOrderItemInDB",
    "PurchaseOrderCreate", "PurchaseOrderUpdate", "PurchaseOrderInDB",
    "SalesOrderItemCreate", "SalesOrderItemInDB",
    "SalesOrderCreate", "SalesOrderUpdate", "SalesOrderInDB",
    "GRNItemCreate", "GRNItemInDB", "GRNCreate", "GRNUpdate", "GRNInDB",
    "DeliveryChallanItemCreate", "DeliveryChallanItemInDB",
    "DeliveryChallanCreate", "DeliveryChallanUpdate", "DeliveryChallanInDB",
    "ProformaInvoiceItemCreate", "ProformaInvoiceItemInDB",
    "ProformaInvoiceCreate", "ProformaInvoiceUpdate", "ProformaInvoiceInDB",
    "QuotationItemCreate", "QuotationItemInDB",
    "QuotationCreate", "QuotationUpdate", "QuotationInDB"
]