"""initial

Revision ID: 2a0e4a696ecd
Revises: 
Create Date: 2025-08-06 12:02:46.071153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0e4a696ecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subdomain', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_email', sa.String(), nullable=False),
    sa.Column('primary_phone', sa.String(), nullable=False),
    sa.Column('address1', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pin_code', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('cin_number', sa.String(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('storage_limit_gb', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('date_format', sa.String(), nullable=True),
    sa.Column('financial_year_start', sa.String(), nullable=True),
    sa.Column('company_details_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index('idx_org_status_subdomain', ['status', 'subdomain'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_subdomain'), ['subdomain'], unique=True)

    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.create_index('idx_otp_email_purpose', ['email', 'purpose'], unique=False)
        batch_op.create_index('idx_otp_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_verifications_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_verifications_id'), ['id'], unique=False)

    op.create_table('platform_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('temp_password_hash', sa.String(), nullable=True),
    sa.Column('temp_password_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('force_password_reset', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_users', schema=None) as batch_op:
        batch_op.create_index('idx_platform_user_active', ['is_active'], unique=False)
        batch_op.create_index('idx_platform_user_email', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_platform_users_id'), ['id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address1', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pin_code', sa.String(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('idx_company_org_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_organization_id'), ['organization_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address1', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pin_code', sa.String(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_customer_org_name')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('idx_customer_org_active', ['organization_id', 'is_active'], unique=False)
        batch_op.create_index('idx_customer_org_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_organization_id'), ['organization_id'], unique=False)

    op.create_table('email_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('voucher_type', sa.String(), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.create_index('idx_email_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_notifications_organization_id'), ['organization_id'], unique=False)

    op.create_table('payment_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_terms', schema=None) as batch_op:
        batch_op.create_index('idx_payment_term_org_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_terms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_terms_organization_id'), ['organization_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('is_gst_inclusive', sa.Boolean(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_manufactured', sa.Boolean(), nullable=True),
    sa.Column('drawings_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_product_org_name'),
    sa.UniqueConstraint('organization_id', 'part_number', name='uq_product_org_part_number')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_product_org_active', ['organization_id', 'is_active'], unique=False)
        batch_op.create_index('idx_product_org_hsn', ['organization_id', 'hsn_code'], unique=False)
        batch_op.create_index('idx_product_org_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('temp_password_hash', sa.String(), nullable=True),
    sa.Column('temp_password_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('force_password_reset', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_path', sa.String(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_org_email'),
    sa.UniqueConstraint('organization_id', 'username', name='uq_user_org_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_org_active', ['organization_id', 'is_active'], unique=False)
        batch_op.create_index('idx_user_org_email', ['organization_id', 'email'], unique=False)
        batch_op.create_index('idx_user_org_username', ['organization_id', 'username'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address1', sa.String(), nullable=False),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('pin_code', sa.String(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_vendor_org_name')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index('idx_vendor_org_active', ['organization_id', 'is_active'], unique=False)
        batch_op.create_index('idx_vendor_org_name', ['organization_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_org_table_action', ['organization_id', 'table_name', 'action'], unique=False)
        batch_op.create_index('idx_audit_org_timestamp', ['organization_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('contra_vouchers',
    sa.Column('from_account', sa.String(), nullable=False),
    sa.Column('to_account', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_contra_org_voucher_number')
    )
    with op.batch_alter_table('contra_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_contra_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_contra_org_from_account', ['organization_id', 'from_account'], unique=False)
        batch_op.create_index('idx_contra_org_to_account', ['organization_id', 'to_account'], unique=False)
        batch_op.create_index(batch_op.f('ix_contra_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contra_vouchers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contra_vouchers_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('credit_notes',
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('reference_voucher_type', sa.String(), nullable=True),
    sa.Column('reference_voucher_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_cn_org_voucher_number')
    )
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index('idx_cn_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_cn_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_cn_org_vendor', ['organization_id', 'vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('debit_notes',
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('reference_voucher_type', sa.String(), nullable=True),
    sa.Column('reference_voucher_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_dn_org_voucher_number')
    )
    with op.batch_alter_table('debit_notes', schema=None) as batch_op:
        batch_op.create_index('idx_dn_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_dn_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_dn_org_vendor', ['organization_id', 'vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debit_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debit_notes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debit_notes_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('inter_department_vouchers',
    sa.Column('from_department', sa.String(), nullable=False),
    sa.Column('to_department', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_idv_org_voucher_number')
    )
    with op.batch_alter_table('inter_department_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_idv_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_idv_org_from_dept', ['organization_id', 'from_department'], unique=False)
        batch_op.create_index('idx_idv_org_to_dept', ['organization_id', 'to_department'], unique=False)
        batch_op.create_index(batch_op.f('ix_inter_department_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inter_department_vouchers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inter_department_vouchers_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('journal_vouchers',
    sa.Column('entries', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_journal_org_voucher_number')
    )
    with op.batch_alter_table('journal_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_journal_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_vouchers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_vouchers_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('payment_vouchers',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_pv_payment_org_voucher_number')
    )
    with op.batch_alter_table('payment_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_pv_payment_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_pv_payment_org_vendor', ['organization_id', 'vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_vouchers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_vouchers_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('proforma_invoices',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_pi_org_voucher_number')
    )
    with op.batch_alter_table('proforma_invoices', schema=None) as batch_op:
        batch_op.create_index('idx_pi_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_pi_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_proforma_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proforma_invoices_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proforma_invoices_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_po_org_voucher_number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index('idx_po_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_po_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index('idx_po_org_vendor', ['organization_id', 'vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('quotations',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_quotation_org_voucher_number')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index('idx_quotation_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_quotation_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('receipt_vouchers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('receipt_method', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('bank_account', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_rv_org_voucher_number')
    )
    with op.batch_alter_table('receipt_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_rv_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_rv_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_vouchers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_vouchers_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('sales_orders',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_so_org_voucher_number')
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index('idx_so_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_so_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_so_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'product_id', 'location', name='uq_stock_org_product_location')
    )
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index('idx_stock_org_location', ['organization_id', 'location'], unique=False)
        batch_op.create_index('idx_stock_org_product', ['organization_id', 'product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_organization_id'), ['organization_id'], unique=False)

    op.create_table('credit_note_items',
    sa.Column('credit_note_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_note_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_note_items_id'), ['id'], unique=False)

    op.create_table('debit_note_items',
    sa.Column('debit_note_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['debit_note_id'], ['debit_notes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debit_note_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debit_note_items_id'), ['id'], unique=False)

    op.create_table('delivery_challans',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transport_mode', sa.String(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('lr_rr_number', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_dc_org_voucher_number')
    )
    with op.batch_alter_table('delivery_challans', schema=None) as batch_op:
        batch_op.create_index('idx_dc_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_dc_org_date', ['organization_id', 'delivery_date'], unique=False)
        batch_op.create_index('idx_dc_org_so', ['organization_id', 'sales_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_challans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_challans_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_challans_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('goods_receipt_notes',
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('grn_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('challan_number', sa.String(), nullable=True),
    sa.Column('challan_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transport_mode', sa.String(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('lr_rr_number', sa.String(), nullable=True),
    sa.Column('inspection_status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_grn_org_voucher_number')
    )
    with op.batch_alter_table('goods_receipt_notes', schema=None) as batch_op:
        batch_op.create_index('idx_grn_org_date', ['organization_id', 'grn_date'], unique=False)
        batch_op.create_index('idx_grn_org_po', ['organization_id', 'purchase_order_id'], unique=False)
        batch_op.create_index('idx_grn_org_vendor', ['organization_id', 'vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_notes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipt_notes_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('inter_department_voucher_items',
    sa.Column('inter_department_voucher_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inter_department_voucher_id'], ['inter_department_vouchers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inter_department_voucher_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inter_department_voucher_items_id'), ['id'], unique=False)

    op.create_table('proforma_invoice_items',
    sa.Column('proforma_invoice_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['proforma_invoice_id'], ['proforma_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proforma_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proforma_invoice_items_id'), ['id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('delivered_quantity', sa.Float(), nullable=True),
    sa.Column('pending_quantity', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_id'), ['id'], unique=False)

    op.create_table('quotation_items',
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_items_id'), ['id'], unique=False)

    op.create_table('sales_order_items',
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('delivered_quantity', sa.Float(), nullable=True),
    sa.Column('pending_quantity', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_items_id'), ['id'], unique=False)

    op.create_table('delivery_challan_items',
    sa.Column('delivery_challan_id', sa.Integer(), nullable=False),
    sa.Column('so_item_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_challan_id'], ['delivery_challans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['so_item_id'], ['sales_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_challan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_challan_items_id'), ['id'], unique=False)

    op.create_table('goods_receipt_note_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('po_item_id', sa.Integer(), nullable=True),
    sa.Column('ordered_quantity', sa.Float(), nullable=False),
    sa.Column('received_quantity', sa.Float(), nullable=False),
    sa.Column('accepted_quantity', sa.Float(), nullable=False),
    sa.Column('rejected_quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipt_notes.id'], ),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_receipt_note_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_note_items_id'), ['id'], unique=False)

    op.create_table('purchase_vouchers',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('grn_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('transport_mode', sa.String(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('lr_rr_number', sa.String(), nullable=True),
    sa.Column('e_way_bill_number', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipt_notes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_pv_org_voucher_number')
    )
    with op.batch_alter_table('purchase_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_pv_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_pv_org_grn', ['organization_id', 'grn_id'], unique=False)
        batch_op.create_index('idx_pv_org_po', ['organization_id', 'purchase_order_id'], unique=False)
        batch_op.create_index('idx_pv_org_vendor', ['organization_id', 'vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_vouchers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_vouchers_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('sales_vouchers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('delivery_challan_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('place_of_supply', sa.String(), nullable=True),
    sa.Column('transport_mode', sa.String(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('lr_rr_number', sa.String(), nullable=True),
    sa.Column('e_way_bill_number', sa.String(), nullable=True),
    sa.Column('voucher_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['delivery_challan_id'], ['delivery_challans.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_sv_org_voucher_number')
    )
    with op.batch_alter_table('sales_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_sv_org_challan', ['organization_id', 'delivery_challan_id'], unique=False)
        batch_op.create_index('idx_sv_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_sv_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_sv_org_so', ['organization_id', 'sales_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_vouchers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_vouchers_voucher_number'), ['voucher_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_vouchers_voucher_type'), ['voucher_type'], unique=False)

    op.create_table('purchase_returns',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('reference_voucher_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reference_voucher_id'], ['purchase_vouchers.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_pr_org_voucher_number')
    )
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.create_index('idx_pr_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index('idx_pr_org_vendor', ['organization_id', 'vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_returns_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('purchase_voucher_items',
    sa.Column('purchase_voucher_id', sa.Integer(), nullable=False),
    sa.Column('grn_item_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grn_item_id'], ['goods_receipt_note_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_voucher_id'], ['purchase_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_voucher_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_voucher_items_id'), ['id'], unique=False)

    op.create_table('sales_returns',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reference_voucher_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reference_voucher_id'], ['sales_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_sr_org_voucher_number')
    )
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.create_index('idx_sr_org_customer', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('idx_sr_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_voucher_number'), ['voucher_number'], unique=False)

    op.create_table('sales_voucher_items',
    sa.Column('sales_voucher_id', sa.Integer(), nullable=False),
    sa.Column('delivery_challan_item_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_challan_item_id'], ['delivery_challan_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_voucher_id'], ['sales_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_voucher_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_voucher_items_id'), ['id'], unique=False)

    op.create_table('purchase_return_items',
    sa.Column('purchase_return_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_return_items_id'), ['id'], unique=False)

    op.create_table('sales_return_items',
    sa.Column('sales_return_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('taxable_amount', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_return_id'], ['sales_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_return_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_return_items_id'))

    op.drop_table('sales_return_items')
    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_id'))

    op.drop_table('purchase_return_items')
    with op.batch_alter_table('sales_voucher_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_voucher_items_id'))

    op.drop_table('sales_voucher_items')
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_returns_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_id'))
        batch_op.drop_index('idx_sr_org_date')
        batch_op.drop_index('idx_sr_org_customer')

    op.drop_table('sales_returns')
    with op.batch_alter_table('purchase_voucher_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_voucher_items_id'))

    op.drop_table('purchase_voucher_items')
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_returns_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_returns_id'))
        batch_op.drop_index('idx_pr_org_vendor')
        batch_op.drop_index('idx_pr_org_date')

    op.drop_table('purchase_returns')
    with op.batch_alter_table('sales_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_vouchers_voucher_type'))
        batch_op.drop_index(batch_op.f('ix_sales_vouchers_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_sales_vouchers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sales_vouchers_id'))
        batch_op.drop_index('idx_sv_org_so')
        batch_op.drop_index('idx_sv_org_date')
        batch_op.drop_index('idx_sv_org_customer')
        batch_op.drop_index('idx_sv_org_challan')

    op.drop_table('sales_vouchers')
    with op.batch_alter_table('purchase_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_vouchers_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_vouchers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_vouchers_id'))
        batch_op.drop_index('idx_pv_org_vendor')
        batch_op.drop_index('idx_pv_org_po')
        batch_op.drop_index('idx_pv_org_grn')
        batch_op.drop_index('idx_pv_org_date')

    op.drop_table('purchase_vouchers')
    with op.batch_alter_table('goods_receipt_note_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_note_items_id'))

    op.drop_table('goods_receipt_note_items')
    with op.batch_alter_table('delivery_challan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_challan_items_id'))

    op.drop_table('delivery_challan_items')
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_items_id'))

    op.drop_table('sales_order_items')
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_items_id'))

    op.drop_table('quotation_items')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('proforma_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proforma_invoice_items_id'))

    op.drop_table('proforma_invoice_items')
    with op.batch_alter_table('inter_department_voucher_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inter_department_voucher_items_id'))

    op.drop_table('inter_department_voucher_items')
    with op.batch_alter_table('goods_receipt_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_notes_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_notes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipt_notes_id'))
        batch_op.drop_index('idx_grn_org_vendor')
        batch_op.drop_index('idx_grn_org_po')
        batch_op.drop_index('idx_grn_org_date')

    op.drop_table('goods_receipt_notes')
    with op.batch_alter_table('delivery_challans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_challans_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_delivery_challans_organization_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_challans_id'))
        batch_op.drop_index('idx_dc_org_so')
        batch_op.drop_index('idx_dc_org_date')
        batch_op.drop_index('idx_dc_org_customer')

    op.drop_table('delivery_challans')
    with op.batch_alter_table('debit_note_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debit_note_items_id'))

    op.drop_table('debit_note_items')
    with op.batch_alter_table('credit_note_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_note_items_id'))

    op.drop_table('credit_note_items')
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_organization_id'))
        batch_op.drop_index(batch_op.f('ix_stock_id'))
        batch_op.drop_index('idx_stock_org_product')
        batch_op.drop_index('idx_stock_org_location')

    op.drop_table('stock')
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_id'))
        batch_op.drop_index('idx_so_org_status')
        batch_op.drop_index('idx_so_org_date')
        batch_op.drop_index('idx_so_org_customer')

    op.drop_table('sales_orders')
    with op.batch_alter_table('receipt_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_vouchers_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_receipt_vouchers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_vouchers_id'))
        batch_op.drop_index('idx_rv_org_date')
        batch_op.drop_index('idx_rv_org_customer')

    op.drop_table('receipt_vouchers')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_quotations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_quotations_id'))
        batch_op.drop_index('idx_quotation_org_date')
        batch_op.drop_index('idx_quotation_org_customer')

    op.drop_table('quotations')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_organization_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_id'))
        batch_op.drop_index('idx_po_org_vendor')
        batch_op.drop_index('idx_po_org_status')
        batch_op.drop_index('idx_po_org_date')

    op.drop_table('purchase_orders')
    with op.batch_alter_table('proforma_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proforma_invoices_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_proforma_invoices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_proforma_invoices_id'))
        batch_op.drop_index('idx_pi_org_date')
        batch_op.drop_index('idx_pi_org_customer')

    op.drop_table('proforma_invoices')
    with op.batch_alter_table('payment_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_vouchers_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_payment_vouchers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payment_vouchers_id'))
        batch_op.drop_index('idx_pv_payment_org_vendor')
        batch_op.drop_index('idx_pv_payment_org_date')

    op.drop_table('payment_vouchers')
    with op.batch_alter_table('journal_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_vouchers_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_journal_vouchers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_journal_vouchers_id'))
        batch_op.drop_index('idx_journal_org_date')

    op.drop_table('journal_vouchers')
    with op.batch_alter_table('inter_department_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inter_department_vouchers_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_inter_department_vouchers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_inter_department_vouchers_id'))
        batch_op.drop_index('idx_idv_org_to_dept')
        batch_op.drop_index('idx_idv_org_from_dept')
        batch_op.drop_index('idx_idv_org_date')

    op.drop_table('inter_department_vouchers')
    with op.batch_alter_table('debit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debit_notes_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_debit_notes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_debit_notes_id'))
        batch_op.drop_index('idx_dn_org_vendor')
        batch_op.drop_index('idx_dn_org_date')
        batch_op.drop_index('idx_dn_org_customer')

    op.drop_table('debit_notes')
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_id'))
        batch_op.drop_index('idx_cn_org_vendor')
        batch_op.drop_index('idx_cn_org_date')
        batch_op.drop_index('idx_cn_org_customer')

    op.drop_table('credit_notes')
    with op.batch_alter_table('contra_vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contra_vouchers_voucher_number'))
        batch_op.drop_index(batch_op.f('ix_contra_vouchers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contra_vouchers_id'))
        batch_op.drop_index('idx_contra_org_to_account')
        batch_op.drop_index('idx_contra_org_from_account')
        batch_op.drop_index('idx_contra_org_date')

    op.drop_table('contra_vouchers')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index('idx_audit_org_timestamp')
        batch_op.drop_index('idx_audit_org_table_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_organization_id'))
        batch_op.drop_index(batch_op.f('ix_vendors_name'))
        batch_op.drop_index(batch_op.f('ix_vendors_id'))
        batch_op.drop_index('idx_vendor_org_name')
        batch_op.drop_index('idx_vendor_org_active')

    op.drop_table('vendors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_org_username')
        batch_op.drop_index('idx_user_org_email')
        batch_op.drop_index('idx_user_org_active')

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_organization_id'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index('idx_product_org_name')
        batch_op.drop_index('idx_product_org_hsn')
        batch_op.drop_index('idx_product_org_active')

    op.drop_table('products')
    with op.batch_alter_table('payment_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_terms_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payment_terms_id'))
        batch_op.drop_index('idx_payment_term_org_name')

    op.drop_table('payment_terms')
    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_notifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_email_notifications_id'))
        batch_op.drop_index('idx_email_org_status')

    op.drop_table('email_notifications')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index('idx_customer_org_name')
        batch_op.drop_index('idx_customer_org_active')

    op.drop_table('customers')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_organization_id'))
        batch_op.drop_index(batch_op.f('ix_companies_id'))
        batch_op.drop_index('idx_company_org_name')

    op.drop_table('companies')
    with op.batch_alter_table('platform_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_users_id'))
        batch_op.drop_index(batch_op.f('ix_platform_users_email'))
        batch_op.drop_index('idx_platform_user_email')
        batch_op.drop_index('idx_platform_user_active')

    op.drop_table('platform_users')
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_verifications_id'))
        batch_op.drop_index(batch_op.f('ix_otp_verifications_email'))
        batch_op.drop_index('idx_otp_expires')
        batch_op.drop_index('idx_otp_email_purpose')

    op.drop_table('otp_verifications')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_subdomain'))
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))
        batch_op.drop_index('idx_org_status_subdomain')

    op.drop_table('organizations')
    # ### end Alembic commands ###