# New: v1/migrations/versions/3c957d567816_add_voucher_type_to_salesvoucher.py

"""add_voucher_type_to_salesvoucher

Revision ID: 3c957d567816
Revises: 269469f1c9c6
Create Date: 2025-08-05 21:00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3c957d567816'
down_revision = '269469f1c9c6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_vouchers', sa.Column('voucher_type', sa.String(), nullable=False, server_default='sales'))
    op.create_index('idx_sv_voucher_type', 'sales_vouchers', ['voucher_type'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sv_voucher_type', table_name='sales_vouchers')
    op.drop_column('sales_vouchers', 'voucher_type')
    # ### end Alembic commands ###